### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by AlvinKuruvilla** [AlvinKuruvilla/kmlog#5]
We may want to do this. 
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py

**Comment by rishvantsingh** [comment]
I am doing this and will push the changes.

**Comment by rishvantsingh** [comment]
Hii @AlvinKuruvilla . I have generated the PR . yOU CAN REVIEW AND MERGE IT.

**Comment by AlvinKuruvilla** [comment]
Solved by #6

**Comment by AlvinKuruvilla** [comment]
It looks like there is an issue with no module named venv on the python 2.7 build
